# Aplicações práticas

# 2.15 Exercício 15: Associação entre Cinto Ferimentos por Localização e Sexo

## A. Enunciado 

Numa amostra aleatória de 68,699 passageiros envolvidos em acidentes de viação, pretende-se analisar a associação existente entre o uso de cinto de segurança (1. Não, 2. Sim) e a ocorrência ou não de ferimentos graves (1. Não, 2. Sim), segmentada pela localização (1. Urbana, 2. Rural) e pelo sexo (1. Mulher, 2. Homem). A informação encontra-se na linha Count da Tabela 1 e no ficheiro "cap02_exerc15_Cinto Ferimentos Localização Sexo.sav" do SPSS e também estão organizados em um dicionário em Python.

# Resolução em Python

## Carregando Bibliotecas

In [1]:
import pandas as pd  # Fornece DataFrames e Series para manipulação de dados em Python, facilitando operações como leitura, escrita, e manipulação de estruturas de dados tabulares.

## Funções Personalizadas

In [2]:
!pip install socialdataanalysis
!pip install --upgrade socialdataanalysis
from socialdataanalysis import gerar_tabela_contingencia
from socialdataanalysis import complementar_tabela_contingencia_com_analise_estatistica
from socialdataanalysis import complementar_e_filtrar_tabelas_contingencia
from socialdataanalysis import analisar_frequencias_esperadas
from socialdataanalysis import eliminacao_reversa_com_comparacao_llm
from socialdataanalysis import calcular_e_exibir_odds_ratios_llm
from socialdataanalysis import criar_tabela_contingencia_expandida_llm

## Dados Fornecidos

In [3]:
# Dicionário com dados categorizados representando grupos e suas frequências
dados = {
    'Sexo': [1, 1, 1, 1, 1, 1, 1, 1,
             2, 2, 2, 2, 2, 2, 2, 2,],
    'Localização': [1, 1, 1, 1, 2, 2, 2, 2,
                    1, 1, 1, 1, 2, 2, 2, 2,],
    'Cinto': [1, 1, 2, 2, 1, 1, 2, 2,
              1, 1, 2, 2, 1, 1, 2, 2,],
    'Feridos': [1, 2, 1, 2, 1, 2, 1, 2,
                1, 2, 1, 2, 1, 2, 1, 2,],
    'Freq': [7287, 996, 11587, 759, 3246, 973, 6134, 757, 
             10381, 812, 10969, 380, 6123, 1084, 6693, 513]
}

# Criando o DataFrame a partir do dicionário
dados = pd.DataFrame(dados)

# Convertendo as colunas para inteiros, se necessário
dados = dados.astype(int)

# Visualizando o dataframe
display(dados)

    Sexo  Localização  Cinto  Feridos   Freq
0      1            1      1        1   7287
1      1            1      1        2    996
2      1            1      2        1  11587
3      1            1      2        2    759
4      1            2      1        1   3246
5      1            2      1        2    973
6      1            2      2        1   6134
7      1            2      2        2    757
8      2            1      1        1  10381
9      2            1      1        2    812
10     2            1      2        1  10969
11     2            1      2        2    380
12     2            2      1        1   6123
13     2            2      1        2   1084
14     2            2      2        1   6693
15     2            2      2        2    513

## Tabela 1: Tabela de Contingência

In [4]:
# Obter automaticamente os nomes dos grupos e da coluna de frequência
grupos = dados.columns[:-1].tolist()  # Todos exceto a última coluna
categorias = {
    grupos[0]: ['1. Mulher', '2. Homem'],
    grupos[1]: ['1. Urbana', '2. Rural'],
    grupos[2]: ['1. Não', '2. Sim'],
    grupos[3]: ['1. Não', '2. Sim']
}

tabela_contingencia = gerar_tabela_contingencia(dados, grupos, categorias)

display(tabela_contingencia)

Feridos                       1. Não  2. Sim
Sexo      Localização Cinto
1. Mulher 1. Urbana   1. Não    7287     996
                      2. Sim   11587     759
          2. Rural    1. Não    3246     973
                      2. Sim    6134     757
2. Homem  1. Urbana   1. Não   10381     812
                      2. Sim   10969     380
          2. Rural    1. Não    6123    1084
                      2. Sim    6693     513

## Tabela de Contingência com Cálculos

In [5]:
complementar_e_filtrar_tabelas_contingencia(tabela_contingencia, complementar_tabela_contingencia_com_analise_estatistica)

Feridos                                       1. Não  2. Sim    Total
Sexo      Localização Cinto
1. Mulher 1. Urbana   1. Não Count            7287.0   996.0   8283.0
                             Expected Count   7578.3   704.7   8283.0
                             % within Cinto     88.0    12.0    100.0
                      2. Sim Count           11587.0   759.0  12346.0
                             Expected Count  11295.7  1050.3  12346.0
                             % within Cinto     93.9     6.1    100.0
                      Total  Count           18874.0  1755.0  20629.0
                             Expected Count  18874.0  1755.0  20629.0
                             % within Cinto     91.5     8.5    100.0
          2. Rural    1. Não Count            3246.0   973.0   4219.0
                             Expected Count   3562.0   657.0   4219.0
                             % within Cinto     76.9    23.1    100.0
                      2. Sim Count            6134.0   757.0   6891.0
                             Expected Count   5818.0  1073.0   6891.0
                             % within Cinto     89.0    11.0    100.0
                      Total  Count            9380.0  1730.0  11110.0
                             Expected Count   9380.0  1730.0  11110.0
                             % within Cinto     84.4    15.6    100.0
2. Homem  1. Urbana   1. Não Count           10381.0   812.0  11193.0
                             Expected Count  10601.1   591.9  11193.0
                             % within Cinto     92.7     7.3    100.0
                      2. Sim Count           10969.0   380.0  11349.0
                             Expected Count  10748.9   600.1  11349.0
                             % within Cinto     96.7     3.3    100.0
                      Total  Count           21350.0  1192.0  22542.0
                             Expected Count  21350.0  1192.0  22542.0
                             % within Cinto     94.7     5.3    100.0
          2. Rural    1. Não Count            6123.0  1084.0   7207.0
                             Expected Count   6408.4   798.6   7207.0
                             % within Cinto     85.0    15.0    100.0
                      2. Sim Count            6693.0   513.0   7206.0
                             Expected Count   6407.6   798.4   7206.0
                             % within Cinto     92.9     7.1    100.0
                      Total  Count           12816.0  1597.0  14413.0
                             Expected Count  12816.0  1597.0  14413.0
                             % within Cinto     88.9    11.1    100.0
Total     Total       1. Não Count           27037.0  3865.0  30902.0
                             Expected Count  28079.6  2822.4  30902.0
                             % within Cinto     87.5    12.5    100.0
                      2. Sim Count           35383.0  2409.0  37792.0
                             Expected Count  34340.4  3451.6  37792.0
                             % within Cinto     93.6     6.4    100.0
                      Total  Count           62420.0  6274.0  68694.0
                             Expected Count  62420.0  6274.0  68694.0
                             % within Cinto     90.9     9.1    100.0

<font color="blue">    
    
### 2.15.1. Pressupostos dos testes do Qui-Quadrado
</font>

<font color="blue">
    
#### a) Verificar a observância dos pressupostos dos testes do Qui-Quadrado.
</font>

In [6]:
analisar_frequencias_esperadas(tabela_contingencia)

Análise para: 1. Mulher


Fo: Feridos  1. Não  2. Sim
Cinto
1. Não     7287     996
2. Sim    11587     759

Fe: Feridos   1. Não  2. Sim
Cinto
1. Não    7578.3   704.7
2. Sim   11295.7  1050.3

 a. 0 células (0.00%) têm uma frequência esperada menor que 5. A frequência esperada mínima é 704.67.
----------------------------------------------------------------------------------------------------

Análise para: 1. Mulher


Fo: Feridos  1. Não  2. Sim
Cinto
1. Não     3246     973
2. Sim     6134     757

Fe: Feridos  1. Não  2. Sim
Cinto
1. Não   3562.0   657.0
2. Sim   5818.0  1073.0

 a. 0 células (0.00%) têm uma frequência esperada menor que 5. A frequência esperada mínima é 656.96.
----------------------------------------------------------------------------------------------------

Análise para: 2. Homem


Fo: Feridos  1. Não  2. Sim
Cinto
1. Não    10381     812
2. Sim    10969     380

Fe: Feridos   1. Não  2. Sim
Cinto
1. Não   10601.1   591.9
2. Sim   10748.9   600.1

 a. 0 células (0.00%) têm uma frequência esperada menor que 5. A frequência esperada mínima é 591.88.
----------------------------------------------------------------------------------------------------

Análise para: 2. Homem


Fo: Feridos  1. Não  2. Sim
Cinto
1. Não     6123    1084
2. Sim     6693     513

Fe: Feridos  1. Não  2. Sim
Cinto
1. Não   6408.4   798.6
2. Sim   6407.6   798.4

 a. 0 células (0.00%) têm uma frequência esperada menor que 5. A frequência esperada mínima é 798.44.
----------------------------------------------------------------------------------------------------

<font color="blue">    
    
### 2.15.2. Modelo loglinear
</fonte>

<font color="blue">
    
#### b) A exploração do modelo loglinear que melhor define a associação entre as variáveis, para explorar a existência de interação entre as variáveis. 

</font>

In [7]:
satured_model, adjusted_model = eliminacao_reversa_com_comparacao_llm(dados, display_models=True, compare_models=False)

Modelo Saturado:
                  Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                   Freq   No. Observations:                   16
Model:                            GLM   Df Residuals:                        0
Model Family:                 Poisson   Df Model:                           15
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -76.730
Date:                Sat, 25 May 2024   Deviance:                  -6.8225e-12
Time:                        20:23:10   Pearson chi2:                 6.86e-22
No. Iterations:                     6   Pseudo R-squ. (CS):              1.000
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         10.8784      0.466     23.366      0.000       9.966      11.791
Sexo                               0.7247      0.299      2.426      0.015       0.139       1.310
Localização                       -2.4356      0.306     -7.950      0.000      -3.036      -1.835
Cinto                              0.9367      0.302      3.106      0.002       0.346       1.528
Feridos                           -1.8102      0.402     -4.506      0.000      -2.598      -1.023
Sexo:Localização                   0.5171      0.193      2.681      0.007       0.139       0.895
Sexo:Cinto                        -0.0619      0.199     -0.311      0.756      -0.452       0.328
Sexo:Feridos                      -0.3816      0.263     -1.450      0.147      -0.897       0.134
Localização:Cinto                  0.5924      0.196      3.018      0.003       0.208       0.977
Localização:Feridos                1.0349      0.256      4.039      0.000       0.533       1.537
Cinto:Feridos                     -0.3756      0.267     -1.406      0.160      -0.899       0.148
Sexo:Localização:Cinto            -0.2679      0.127     -2.106      0.035      -0.517      -0.019
Sexo:Localização:Feridos          -0.0977      0.165     -0.591      0.554      -0.421       0.226
Sexo:Cinto:Feridos                -0.2081      0.180     -1.156      0.248      -0.561       0.145
Localização:Cinto:Feridos         -0.2811      0.169     -1.659      0.097      -0.613       0.051
Sexo:Localização:Cinto:Feridos     0.1292      0.112      1.151      0.250      -0.091       0.349
==================================================================================================
Passo 1: Removendo Sexo:Cinto com p-valor 0.756
Passo 2: Removendo Sexo:Localização:Feridos com p-valor 0.063

Modelo Ajustado:
                  Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                   Freq   No. Observations:                   16
Model:                            GLM   Df Residuals:                        2
Model Family:                 Poisson   Df Model:                           13
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -78.501
Date:                Sat, 25 May 2024   Deviance:                       3.5428
Time:                        20:23:10   Pearson chi2:                     3.55
No. Iterations:                     6   Pseudo R-squ. (CS):              1.000
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         10.8315      0.199     54.362      0.000      10.441      11.222
Sexo                               0.7455      0.079      9.413      0.000       0.590       0.901
Localização                       -2.3058      0.134    -17.204      0.000      -2.568      -2.043
Cinto                              0.8609      0.099      8.732      0.000       0.668       1.054
Feridos                           -1.7014      0.160    -10.663      0.000      -2.014      -1.389
Sexo:Localização                   0.4375      0.051      8.529      0.000       0.337       0.538
Sexo:Feridos                      -0.4431      0.067     -6.608      0.000      -0.575      -0.312
Localização:Cinto                  0.5749      0.082      6.978      0.000       0.413       0.736
Localização:Feridos                0.8783      0.082     10.681      0.000       0.717       1.039
Cinto:Feridos                     -0.3481      0.098     -3.542      0.000      -0.541      -0.155
Sexo:Localização:Cinto            -0.2625      0.033     -7.848      0.000      -0.328      -0.197
Sexo:Cinto:Feridos                -0.2380      0.041     -5.831      0.000      -0.318      -0.158
Localização:Cinto:Feridos         -0.2399      0.066     -3.629      0.000      -0.369      -0.110
Sexo:Localização:Cinto:Feridos     0.1078      0.029      3.688      0.000       0.051       0.165
==================================================================================================

<font color="blue">
    
#### c) A confirmação do modelo escolhido.
</font>

In [8]:
satured_model, adjusted_model = eliminacao_reversa_com_comparacao_llm(dados, display_models=False, compare_models=True)

Comparação entre Modelos Saturado e Ajustado:

AIC Modelo Saturado: 185.46
AIC Modelo Ajustado: 185.00

Teste de Razão de Verossimilhança (LRT):

LR stat: 3.543, Diferença no Número de Parâmetros: 2, p-value: 0.170

<font color="blue">
    
#### d) A significância da associação e sua intensidade através do odds rácio.
- d.1) (Cinto\*Localização\*Sexo)
- d.2) (Cinto\*Ferimento\*Localização)
- d.3) (Ferimento\*Sexo)
</font>

In [9]:
calcular_e_exibir_odds_ratios_llm(adjusted_model)

Odds Ratios (ORs) e Intervalos de Confiança (ICs) de 95%:

--------------------------------------------------------------------------------
Intercept: OR=50589.178, IC 95%=(34233.982, 74758.027)
--------------------------------------------------------------------------------
Sexo: OR=2.107, IC 95%=(1.804, 2.461)
--------------------------------------------------------------------------------
Localização: OR=0.100, IC 95%=(0.077, 0.130)
--------------------------------------------------------------------------------
Cinto: OR=2.365, IC 95%=(1.950, 2.870)
--------------------------------------------------------------------------------
Feridos: OR=0.182, IC 95%=(0.133, 0.249)
--------------------------------------------------------------------------------
Sexo:Localização: OR=1.549, IC 95%=(1.401, 1.713)
--------------------------------------------------------------------------------
Sexo:Feridos: OR=0.642, IC 95%=(0.563, 0.732)
--------------------------------------------------------------------------------
Localização:Cinto: OR=1.777, IC 95%=(1.512, 2.088)
--------------------------------------------------------------------------------
Localização:Feridos: OR=2.407, IC 95%=(2.049, 2.828)
--------------------------------------------------------------------------------
Cinto:Feridos: OR=0.706, IC 95%=(0.582, 0.856)
--------------------------------------------------------------------------------
Sexo:Localização:Cinto: OR=0.769, IC 95%=(0.720, 0.821)
--------------------------------------------------------------------------------
Sexo:Cinto:Feridos: OR=0.788, IC 95%=(0.728, 0.854)
--------------------------------------------------------------------------------
Localização:Cinto:Feridos: OR=0.787, IC 95%=(0.691, 0.896)
--------------------------------------------------------------------------------
Sexo:Localização:Cinto:Feridos: OR=1.114, IC 95%=(1.052, 1.180)
--------------------------------------------------------------------------------

In [10]:
df_ext = criar_tabela_contingencia_expandida_llm(dados, grupos, categorias, adjusted_model)
df_ext

                             observed         expected          residuals
                               1. Não 2. Sim    1. Não   2. Sim    1. Não
Sexo      Localização Cinto
1. Mulher 1. Urbana   1. Não     7287    996   7315.64  1005.75    -28.64  \
                      2. Sim    11587    759  11534.29   773.32     52.71
          2. Rural    1. Não     3246    973   3255.75   944.05     -9.75
                      2. Sim     6134    757   6148.32   761.88    -14.32
2. Homem  1. Urbana   1. Não    10381    812  10352.36   802.25     28.64
                      2. Sim    10969    380  11021.71   365.68    -52.71
          2. Rural    1. Não     6123   1084   6113.25  1112.95      9.75
                      2. Sim     6693    513   6678.68   508.12     14.32


                             2. Sim
Sexo      Localização Cinto
1. Mulher 1. Urbana   1. Não  -9.75
                      2. Sim -14.32
          2. Rural    1. Não  28.95
                      2. Sim  -4.88
2. Homem  1. Urbana   1. Não   9.75
                      2. Sim  14.32
          2. Rural    1. Não -28.95
                      2. Sim   4.88